services:
  - type: web
    name: event-management-web
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_BASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: event_management
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
